services:
  - type: web
    name: youtube-downloader-api

    env: node

    rootDir: backend

    buildCommand: |
      npm install
      pip install yt-dlp

    startCommand: npm start
